---
title: "Mid-term Exam"
linktitle: "Mid-term exam"
due_date: "2023-03-22"
due_time: "11:35 AM"
output:
  blogdown::html_page:
    toc: false
menu:
  assignment:
    parent: Exam
    weight: 1
type: docs
---

We only have one exam this semester. It will cover all content from Modules 1 and 2. This includes our coverage of insurance purchases and insurance markets (risk aversion, the risk premium and willingness to pay, and adverse selection), as well as our coverage of physician agency (agency under fee-for-service payments, capitated payments, and fixed prices). 

## Format
- The exam will consist of at least 5 general problems, each with between 3 and 5 individual questions. I anticipate 20 to 25 questions in total. Just as we've done in our homework assignments, some of these will require you to solve an optimization problem, some will require a brief explanation, and some parts will require you to draw a graph. See the [content](#content) section below for more information.

## Content {#content}
- The overall content of the exam will match very closely the content that we've covered in class and in our homework assignments. The homework and the in-class worksheets should be excellent practice for the exam. I will also post an exam review sheet to the [resources](/resource/) page sometime before the week of the exam, and we'll have time to review this in class.

- Many questions will have some element in which you are asked to examine a real-world health policy in the context of the problem. We will practice this in class and in your homework assignments as well, so it should be nothing new by the time the exam comes.

- Due to time constraints, I **will not** ask you to collect or work with any data on the exam.
