---
title: "Final Project"
linktitle: "Final project"
due_date: "2023-04-24"
due_time: "11:59 PM"
output:
  blogdown::html_page:
    toc: false
menu:
  assignment:
    parent: Project
    weight: 1
type: docs
---

This year, the final project is a 2-page policy brief. This is a big part of your grade and essentially replaces what would otherwise be a final exam. Please start as early as possible and save yourself lots of stress in April! Big thanks to [Prof. Rebecca Kreitzer](https://www.rebeccakreitzer.com/) for making her policy brief assignment publicly available on her website, which was the basis for our project.

The goals of the policy brief are three-fold:

1. Learn about and effectively communicate information about a health and/or healthcare problem and potential policy solutions that you are interested in.
2. Learn practical skills about policy communication, data and information visualization, and editing.
3. Learn ways to empower yourself and share your voice on issues you care about  

# Overview
A policy brief is a short publication to provide policymakers and other interested parties with research and evidence about a specific policy issue. Policy briefs pack a lot of key information into an easily digestible package, simplifying complex policy problems so that they can be better understood and debated.  Because policy makers have limited time to become informed on a wide range of issues, briefs are a tool used to succinctly convey information about what the issue is, what research has been done, what the range of possible policy alternatives are, and what the best policy would be.

Policy briefs should be timely — addressing issues that are currently being faced at the local, regional, or national levels. They should also balance being informative and sufficiently nuanced while not being overly technical or complicated. The best policy briefs are visually engaging, well-organized, easy to navigate, and memorable.

The term "policy brief" can mean many things. In this class, a policy brief is a succinct 1-2 page document that

- Targets a non-technical audience including policymakers and stakeholders
- Provides an overview rather than specifics with enough information that someone can become relatively informed about an issue and have some idea of how to address it
- Raises awareness of an issue and potential policy solutions

To help stay on track throughout the semester, we've divided the brief into three stages. Please use the links (or just navigate below) for details of each stage. Please also check out the section on [Other Resources] for additional information, including examples of policy briefs and other guides.

1. [Annotated Bibliography], due on **March 1** and worth **20 points** toward your final project grade
2. [Factsheet], due on **April 3** and worth **40 points** toward your final project grade
3. [Final Policy Brief], due on **April 24** and worth **80 points** toward your final project grade

# Annotated Bibliography
Step 1 is to identify a topic and create an annotated bibliography. This bibliography should organize the relevant sources to be included in your policy brief. You should include both an overview of the topic of your choice — a short paragraph no longer than six sentences — as well as an annotated bibliography including 8-10 high quality sources. At least 6 of those sources must be scholarly articles. Please see our [workshop slides](https://imccart.github.io/econ372-content/policy-brief/annotated-bibliography-workshop.pdf) for additional information and tips on forming your bibliography.

## Selecting an initial topic
While you have wide discretion to select a topic of your choosing, it should remain within the world of health policy and healthcare markets. Additionally, some ideas are better than others, and some ideas are easier than others. When selecting a topic, ask yourself the following questions: What issues are you passionate about? and Where can your voice make a difference? You will be working on this project for an entire semester, so you should pick something you are excited, inspired, motivated, or angry about rather than something that sounds like it will be easy. Also, you are an undergraduate student at Emory living in Georgia. Are there specific issues where your voice, perspective, or framing is especially useful?

## Narrowing down a topic
Spend a bit of time really thinking about your brief’s direction. You have enough time in the semester to learn about a new policy topic, so don’t feel like you need to pick something you already know a lot about. Here are a few strategies to generate some ideas:

- Read local and national newspapers, newsletters, and magazines to see what issues are getting discussed (or not) in the media
- Review the syllabus to see if there is a topic area within the class to focus your policy brief
- Look at the policy platforms of politicians and political parties at the local, state, or national level
- Talk to people — other people will have seen and heard about different policies than you
- Do some preliminary research — Google the topics you are considering and look at what has already been written, what scholarly research has been done, when was it last updated, is there new information or policy discussion, etc.

Once you have a general topic selected and brief paragraph explaining what this to, you'll need to assemble the bibliography. A traditional bibliography (usually found at the end of a scholarly resource) provides the reader with the author, title, and publication details of a resource. An **annotated** bibliography adds a brief summary about the each of the sources, and it’s usually used for the author’s own reference. The purpose is to compile sources that will support your central argument or theory. The process of creating the annotated bibliography will also help you understand where the research and policy debates currently stand. You don’t need to use the first 8-10 sources you find on the topic. You’d be better suited to find more sources than you need and narrow them down based on relevance, uniqueness of perspective, and quality of the source.

## Selecting sources
Not all sources are equally good. In fact, many sources are bad – some intentionally misleading and others are just plain sloppy. In advocating for "research and evidence-based policy," it’s critical your brief has a solid foundation. There are high quality sources that aren’t scholarly, of course. You may find it very useful to additionally have sources from news organizations, government websites or publications, official reports, and think tanks. The trick here is to really evaluate the quality and impartiality of the source. Look up the background of think tanks and organizations on Wikipedia or other sources and be clear about how the quality of the source shapes the arguments made in the brief.

Your sources should be carefully selected to contribute different pieces to the puzzle. Make sure you have sources about background/context, other sources more on evaluating policy, perhaps some news stories about recent events. You want your brief to be well-rounded and not missing any big gaps in pertinent information. You may not end up using all the sources in your fact sheet and policy brief, but the more sources you identify now, the easier it will be to refine your points. You may also find that as you’re working on your project, you will need to find new sources. Additionally, sources do not have to be on the exact same topic, but they should relate. Remember that there can be regional, political, and socioeconomic differences (to name a few) that might make some work not generally applicable. 

## Writing annotations
The annotated bibliography will serve as the foundation for the basic facts you will outline for the reader to understand the problem at hand, and it will provide the basis of the evidence you provide to substantiate your claims. Basically, the annotated bibliography is a bibliography with a brief summary (i.e., annotation) of each source. Your annotations may include the following information:

- What question do(es) the author(s) seek to answer?
- What is the primary thesis/argument/theory of the work?
- How is this source relevant to my topic? What aspect of my research question/topic does this source illuminate?
- What are the main findings? Are there reasons to doubt the evidence? What are some of the problems (e.g. clarity, methodological issues, out-of-date) with the source?

When writing the annotation, you should provide enough information in about three to five (grammatically correct, full) sentences for readers to obtain an accurate understanding of the source’s purpose, content, and value. It should be clear how this article is contributing to your project; you may want to make this explicit. For each source, you should provide the full bibliographic citation followed by a brief analysis of the source (Citation format is your choice. Just be consistent.)

## Rubric for Annotated Bibliography
The annotated bibliography is worth 20 points toward the final project grade (recall the final project is worth 140 points), divided into two parts:

1. **Policy Overview** (10 points). In no more than 6 sentences, the overview should:
    - describe the problem you will address
    - explain why the problem is important
    - briefly reference an evidence-based policy solution to be considered in the brief

2. **Annotated Bibliography** (10 points). The annotated bibliography must include:
    - minimum of 8 high-quality sources, at least 6 of which are scholarly (academic, peer-reviewed or law review) indicated by **bold font**
    - summarize each source, relevant data, and main contribution to the area of interest
    
    

# Factsheet
Having established a topic and set of sources, stage 2 of the project is to create a 4-page (double-spaced) **fact sheet**. Since your final policy brief should be advocating in favor of a particular policy or set of actions, this should help inform and shape the information you include within this assignment. Your fact sheet should consist of the following four sections:

1. **Why is this an important topic to highlight today?** (10 points). The motivation for a policy brief is to provide policy makers and other interested parties about an important policy issue. Good policy briefs define the policy problem with a sense of purpose and urgency, demonstrating why this topic should be given priority to other topics. This part of the fact sheet should explain the problem using easy-to-follow language and convey the importance/urgency of a solution. Some questions to ask yourself are:
    - What trends should people be aware of?
    - What concepts and vocabulary do we need to fully understand the problem at hand?
    - What is the relevant history of this topic?
    - What are the implications and ramifications of this topic? 
    - Why should we think about this issue in the way you are presenting and not another way?

2. **What is generally known (and not known) about this issue?** (10 points). Oftentimes, you will need to explain, refute, or debunk ideas surrounding a particular issue. This part of the fact sheet should provide relevant background and elaborate on key findings. You should also address questions rooted in myth, misconception, or ignorance — either about the policy itself or the people affected by it.

3. **What should be done to address this issue?** (10 points). Some issues might already have best practices being implemented in another country, in the private sector, or in some states but not others. There will also typically be counterarguments or counter policies to address. An important aspect to think about is how much it might cost to fix the problem — and do the benefits of fixing it outweigh the costs of implementing a solution? This section of the fact sheet should provide information on how the policy is being addressed elsewhere and offer some policy recommendations that are supported by your research.

4. **How are the potential policy solutions shaped by economics?** (10 points). In this section, you should address the incentives introduced by your proposed solution. Who is affected by the policy and how might they respond in an unintended way? Are there some other potential responses that may decrease the effectiveness of the proposed solution? 


# Final Policy Brief
For stage 3, you will craft a professional, concise, and informative advocacy oriented 2-page policy brief on your topic. Your policy brief should draw attention to an important public policy issue within the health and/or healthcare market space; “define” the policy problem with evidence and other relevant context; and provide research and evidence-based policy recommendations or actions that reflect the constraints of the real world. Please see the slides for additional discussion on the policy brief, including examples and other frequently asked questions, [here](https://imccart.github.io/econ372-content/policy-brief/policy-brief-faq.pptx).

The 2-page policy brief is worth 80 points toward you final project grade, allocated as follows:

1. **Problem Definition and Introduction** (15 points). Your introduction of the policy issue to the audience must be catchy/memorable, informative, easy to follow, and convey a sense of urgency.

2. **Main Content** (25 points). The bulk of the brief should elaborate on the policy problem: root causes, trends, the scope of the issue, or other relevant context. The specific content may vary depending on your selected topic, but some basic things to consider include:
    - Relevant data, information, findings, and arguments should provide the reader with a concise, though nuanced overview of the policy issue.
    - The content should reflect insights from high quality source materials (including scholarly sources)
    - The writing should be clear and accurate. Cumulatively, the content should build into a persuasive narrative.

3. **Solution Advocacy** (20 points). The brief should recommend policy solution(s) and/or action(s) that address the policy problem. These recommendations should be supported by your research and should reflect current reality, including a response to notable counterarguments, constraints, or barriers.

4. **Structure & Professionalism** (10 points). The brief should be well organized and easy to navigate for non-subject-matter experts, with very few or no grammatical errors, spelling mistakes, missing words, etc.

5. **Visually Engaging & Memorable** (10 points). There should be an effective use of limited space, with attention drawn to key points and structure using font, color, boxes, or other visual devices. Your final brief must include at least one table and at least one figure/graphic.


From the work on your annotated bibliography, you must also cite at least 8 sources (6 of which are academic, peer-reviewed sources). In-text citations should be in parenthesis, e.g., (McCarthy et al. 2023), and you should include a bibliography as part of the 2-page limit. Citations should be used in the introduction, main content, **and** advocacy sections.


# Other Resources
The best way to become familiar and comfortable with the genre is by exploring it some. This will also be a good way for you to get an idea for the types of topics that policy briefs can cover. 

1. External sources
    - A good source for examples or briefs and/or good idea for brief topics is from the research centers at the [Harvard Kennedy School for Government](https://www.hks.harvard.edu/faculty-research/publications/publications-centers-initiatives), [Princeton School of Public and International Affairs](https://spia.princeton.edu/research-faculty-centers/research-briefs), and research centers at the [University of Michigan Ford School of Public Policy](https://fordschool.umich.edu/research-centers) or the [University of Chicago Harris School](https://harris.uchicago.edu/research-impact/centers-institutes)
    - Explore the “Issues” pages of think tanks like the [Center for American Progress](https://www.americanprogress.org/issues/), the [Institute for Women’s Policy Research](https://iwpr.org/research/), [American Enterprise Institute](https://www.aei.org/policy-areas/), or [National League of Cities](https://www.nlc.org/advocacy/) – just to name a few!
    - Dr. Rebecca Kreitzer’s website also has dozens of examples of completed student policy briefs, available [here](https://www.rebeccakreitzer.com/briefs/).
    - [Research Engagement with Policy Makers: A Practice Guide to Writing Policy Briefs](https://osf.io/m25qp/)
    - ["An Essential Guide to Writing Policy Briefs." International Centre for Policy Advocacy](https://www.icpolicyadvocacy.org/sites/icpa/files/downloads/icpa_policy_briefs_essential_guide.pdf)
    
2. Resources at Emory
    - The Emory Writing Center has tons of resources and support. You can book an appointment for someone to evaluate your work. 
    - Emory libraries have resources on journals, starting research, and have classes for organizing your sources. Chris Palazzolo is our contact with the library and is available if you have questions.
    - Of course, come talk to me or the TA!
